### PR TITLE
fix iOS build

### PR DESCRIPTION
**Pull request by aehlke**

### CODE REVIEW

**Comment by dagronf** [comment]
This library doesn't currently support iOS at all (look at the Package.swift `platforms` section). It was written (and tested) only on macOS so I'm cautious about checking this one in.

How are you trying to use this library?

**Comment by dagronf** [comment]
Ah. I see the problem you're seeing.

For clarity that the library only supports macOS, I'd rather `#if os(macOS)` the entire content of the file that doesn't currently compile on an iOS target. (which is also consistent with the rest of the code)

I've just pushed up a new version [(3.4.2)](https://github.com/dagronf/DSFAppearanceManager/compare/3.4.1...3.4.2) which fixes the build.

Many thanks for alerting me to this issue!

**Comment by aehlke** [comment]
I'm using https://github.com/dagronf/DSFStepperView (wonderful work, thank you for it) which depends on this and fails the iOS build. Maybe better is to exclude this dependency from iOS builds in DSFStepperView

**Comment by dagronf** [comment]
@aehlke  Ah! Of course, that makes sense. Thanks for letting me know.  

I've just checked the DSFStepperView package against the new version of DSFAppearanceManager and all seems well now. Can you please try it out and let me know if it fixes the issue you're seeing?

**Comment by aehlke** [comment]
I haven't tested your branch since I'm now on my own fork but you made the same change I did so I'm certain it's good now, thank you

**Comment by aehlke** [comment]
@dagronf I've switch back to yours and it works, thanks again

**Pull request closed without merging**
